flowchart TD
    A(User input) --> B[Orchestrator appends #91; messages, initial prompt, tools schema , action response #93; to model]
    B --> C[Model interprets]
    C --> D[Thought]
    D --> E[Action]
    E --> |Loop <= 5| I[Tool Request]
    I --> J[Tool Execcution]
    J --> K[Tool Response]
    K --> B
    E -->  |Loop > 5 | Exit
    E -->  |Response achived | Exit
    Exit --> L[Final response to user]
    

 